[package]
name = "nsod"
version = "0.9.0"
edition = "2024"

[lib]
name = "nsod_rust"
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nix = { version = "0.30.1", features = ["process"] }